server:
  port: 8002
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/testcloud
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    # 不要使用下划线
    name: provider-service-nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        ephemeral: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
